Add files via upload
 org.json.JSONException: Value <br of type java.lang.String cannot be converted to JSONObject

to solve "end of input at character 0" .. make sure you have an else if statement eg.. 
else if(success.equals("0")){.....}